// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Teacher interface {
	IsTeacher()
}

type ClassTeacher struct {
	Name  string `json:"name"`
	Class string `json:"class"`
}

func (ClassTeacher) IsTeacher() {}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type SubjectTeacher struct {
	Name    string `json:"name"`
	Subject string `json:"subject"`
}

func (SubjectTeacher) IsTeacher() {}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
